### ISSUE TITLE
I wanna play your game! 😅

### ISSUE THREAD

**Issue by LDubya** [susanBuck/e28-fall20#10]
drop your jsfiddle?

###### ps I know that I can just clone your e28 repo.. But clicking on a hyperlink is easier 😃

**Comment by iamakimmer** [comment]
Is there a way to see where your jsfiddle is from the quiz?   I can't see my submitted answers and I think I created the jsfiddle anonymously 😅

**Comment by susanBuck** [comment]
I'll be compiling and sharing a list of all games after grading. : )

**Comment by LDubya** [comment]
sounds good ^_^
