### ISSUE TITLE
🎃 👻 🧛 🧟 Who else wants to make Project 1 Halloween themed?! 

### ISSUE THREAD

**Issue by ARuzek** [susanBuck/e28-fall20#12]
Haunted houses?
Witch's brew?
Broomsticks?
Zombies?
Candy?

Leave more ideas for spook-tacular games in the comments 😄

**Comment by gabrielajohnson** [comment]
Sounds good to me! Changing all of my rock, paper, scissors options to Halloween options would be fun 🎃

**Comment by susanBuck** [comment]
Fun! : )

**Comment by LDubya** [comment]
sounds fun, count me in!

**Comment by Ashley877** [comment]
Love this idea!!

**Comment by ColeDCrawford** [comment]
Saw my first pumpkin outside this week, but it still feels like summer in the northeast!
