### ISSUE TITLE
Buddy as CI/CD for DigitalOcean

### ISSUE THREAD

**Issue by gboie** [susanBuck/e28-fall20#13]
I had no choice but deploying on a Digital Ocean droplet my week 2 assignment, and discovered a few cool things in the process. I tried Drone and Buddy for rapid deployment, on each GitHub repo push, to my web server in the droplet and Buddy https://buddy.works/ is a clear winner. You can setup a pipeline in the UI in minutes and then on each push your code will be deployed, I can help if anyone is interested on setting this up.

**Comment by R-Elijah** [comment]
I am a lot more familiar with Jenkins and this is the first time I've heard of Buddy. Thank you for the tip, it looks quite interesting!

**Comment by gboie** [comment]
Jenkins is a great tool, but then you have to install, configure, etc. Buddy is a Saas based ready to use CI/CD platform. Please let me know if there is anything I can do to help if you decide to use it.

**Comment by susanBuck** [comment]
Just a quick note since I just covered the production server and a deployment process in the Week 4 videos posted yesterday:

Students are welcome to explore Buddy if they want a more automated deploy process than the one I showed. : )

**Comment by gboie** [comment]
Using Buddy, almost feels like cheating, since I am skipping the git ssh key configuration on the server itself, and configure the git connectivity on Buddy pipeline settings. After that I am just configuring the pipeline to deploy at every push (that can be obviously customized, probably no one would want to continue deploy on a prod server). Here to help if anyone wants to give it a try.

**Comment by ColeDCrawford** [comment]
This looks really good. I haven't found a CI/CD pipeline I love yet but looking forward to trying this out.

**Comment by LDubya** [comment]
> https://buddy.works/ 

ooh `.works` is a super interesting TLD 👀

**Comment by susanBuck** [comment]
Going to close this thread as I think everyone has had a chance to see it, but feel free to keep the discussion going!
