### ISSUE TITLE
Week 3 lecture follow-up: Vue 3 released!

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-fall20#14]
For those of you who've watched this week's (13) lecture videos, you'll recall my discussion on how Vue 3.0 was soon to be released, but we didn't know exactly when yet.

Well, now we know - Vue 3.0 was released on Friday. : )

Here are the release notes: <https://github.com/vuejs/vue-next/releases/tag/v3.0.0>

Given this, I wanted to highlight a few points from lecture:
+ I will be adapting this semester's material so you'll walk away with an understanding of Vue 2 *and* Vue 3
+ Vue 3 is not a dramatic change from Vue 2 - it's mostly additive
+ It's important to still understand Vue 2 as we will encounter projects and examples written in it for a while

More on this topic in coming weeks!

**Comment by gboie** [comment]
The Vue cheat sheets you suggested are really cool! They seem to be targeting V2 only, I am guessing new ones will come up soon for v3 as well?

**Comment by susanBuck** [comment]
@gboie For sure!

For example: https://www.vuemastery.com/pdf/Vue-3-Cheat-Sheet.pdf

I didn't include this one in the assignment because it's pretty specific to the Composition API aspect of Vue 3, which is something we won't get to until later in the semester.
