### ISSUE TITLE
Reusing Domain and Digital Ocean Droplet From e2

### ISSUE THREAD

**Issue by pllealfunes** [susanBuck/e28-fall20#16]
Hi @susanBuck, I'm also taking your e2 course and I was wondering if I could reuse my domain name and Digital Ocean droplet for this course? Would this be possible because we are going to be using subdomains or would it could cause issues that are best to avoid?

**Comment by susanBuck** [comment]
Hi @pllealfunes -

Yes, you can absolutely re-use the same domain and server. Since the project specifications include the course identifier as part of the subdomain (e.g. *the e2p1.yourdomain.com* or *e28.p1.yyourdomain.com*) you won't run into any conflicts.

**Comment by pllealfunes** [comment]
That's great thank you so much!
