### ISSUE TITLE
Check out your classmate's JS Games from Assignment 2

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-fall20#17]
Hi everyone,

I wanted to share a round-up of the games your classmates created in the Week 2 assignment. 

First, some high/low number guessing games. I suggest skimming through some of these just the compare/contrast the various different approaches:
+ https://jsfiddle.net/andymbryant/50m8yset/12/
+ https://jsfiddle.net/spjmaz24/
+ https://jsfiddle.net/ccianelli22/sxd3z76g/
+ https://jsfiddle.net/cdc43339/L2yu0dt4/74/
+ https://jsfiddle.net/sandeepan/4z7bhmt8/2/
+ https://jsfiddle.net/sjanvey/nxks5wrh/
+ https://jsfiddle.net/cauv7kh6/
+ https://jsfiddle.net/AntonieKowal/wnx5e6sj/7/
+ https://jsfiddle.net/vmorris412/vdq42an8/6/
+ https://jsfiddle.net/67d0b4ce/
+ https://jsfiddle.net/sg3acwky/42/
+ https://jsfiddle.net/Wertoma/cshr451d/6/
+ https://jsfiddle.net/haz285/6zLkef41/3/

Next, some good 'ole Rock Paper Scissors games:
+ https://jsfiddle.net/Boubisto/xwLsp1tu/4
+ https://jsfiddle.net/adejeffchen/51vauzf4
+ https://jsfiddle.net/michaelkchen/ao1qb360/
+ https://jsfiddle.net/alexanderegiannini/hzrea82m/11/
+ https://jsfiddle.net/sg7788/uL8g10t7/4/
+ https://jsfiddle.net/9ukva8rn/ (This one does use some image assets, so it doesn't work so well is JSFiddle)
+ https://jsfiddle.net/kepsuwr0/
+ https://jsfiddle.net/gabrielajohnson/o4sdmqLk/2/
+ https://jsfiddle.net/9uzbrow7/ (Technically, Rock Paper Scissors Lizard Spock :)
+ https://jsfiddle.net/plleal/cfjp7x12/
+ https://jsfiddle.net/adamngu/32h8vwa4/1/
+ http://jsfiddle.net/erstan/qbnhjvc8/

And a few mystery word games:
+ https://jsfiddle.net/0rzdm9tg/6/
+ https://jsfiddle.net/kxoqdpcf/
+ https://jsfiddle.net/xgp0jLu5/

Now for some games that were "outside the box": 

__Shake the trees!__
Game: <http://aruzek-game.hesweb.xyz> (Doesn't work well on JSFiddle so I threw it on my server)
Code: <https://github.com/ARuzek/e28/tree/master/game>

This game is adorable, and Amelia got super creative with the illustrations and mechanics. So cool.

__Where in the world is the International Space Station?__
Game: <https://gboie.github.io/e28/game>
Code: https://github.com/gboie/e28/tree/master/game

This is a neat game, and Gabe went above and beyond (no pun intended) by tapping into some external APIs. There is a known bug that causes this game to occasionally fail; Gabe's notes on this:

> The problem I ran into is that there are periods of time when Google Geocode API is unable to resolve the ISS's latitude and longitude into an actual location. I am sure that this might be by default when ISS flies above oceans or other uninhabitable and unpopular regions. I have a error message to show that, the key is to come back and try again later.

__Evil Hangman__
https://jsfiddle.net/csloan29/2pcamhxq/
As Carter promises, this game is...evil. : )

__Tic Tac Toe__
https://jsfiddle.net/hula_zell/09fa6mtc/10/
Tic Tac Toe is a fun game to execute, and Eric did a great job here.

__Street Referendum__ 
https://jsfiddle.net/zs0Lx4e9/
A very timely game by Larry, and one you might get a kick out of if you enjoy political humor.

__How fast can you type__
Game: http://heidericklucas-game.hesweb.xyz (Another one that didn't work so well in JSFiddle so I put it on a server)
Code: https://github.com/heidericklucas/e28/tree/master/game
Lucas' game puts your typing skills to the test.

__"Play with a Rainbow! De-stress your Day!"__
https://jsfiddle.net/azombie/f1uc5dL2/60/
The title says it all. Thanks for ending us on a bright note, Elena!

**Comment by adejeffchen** [comment]
Way to go the creative ones!
