### ISSUE TITLE
Interesting read: The Era of Visual Studio Code

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-fall20#18]
Hi everyone,

Came across an interesting post this morning: The [Era of Visual Studio Code](https://blog.robenkleene.com/2020/09/21/the-era-of-visual-studio-code/)

In the post, the author discusses the evolution of code editors, and makes the case that VSCode might be taking root as a code editor with some longevity.

Beyond that, it offers an interesting history of code editors, and also the shift to web based editors.

Will be interesting to watch where things go in the coming years.

Hope everyone has a nice weekend!

**Comment by AdamNgu** [comment]
I moved to Visual Studio Code after using Sublime and Atom and I've never looked back. VSC has revolutionized and drastically sped up my ability to work in JavaScript. Just need to pick up TypeScript and achieve its full potential..

**Comment by ColeDCrawford** [comment]
Been checking out VS Code more after reading this post. I've definitely noticed some major speed increases over Atom.
