### ISSUE TITLE
Receiving Terminal Error 'Failed To Push'

### ISSUE THREAD

**Issue by pllealfunes** [susanBuck/e28-fall20#20]
Hi guys, I'm receiving the following error when I try to make a git push to github. I googled around and a Stackoverflow post suggests to fetch and merge. Can anyone explain to me why this kind of error could occur? I mean I'm the only one pushing and pulling from my e28 so I'm not sure why the error.

> ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:pllealfunes/e28.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by gboie** [comment]
Sounds like your upstream repo has code changes that you didn't pull
locally based on that error. Try a git pull (you might have to stash your
local changes).

Thanks,
Gabriel

**Comment by tostaylo** [comment]
What Gabriel said should work. You may want to look closely at the console when you “git pull”to view what has changed in your repos’s origin branch. You can also look at the last commit in your repo’s origin to see what has changed there and compare that to your latest commits locally. 

As an example, editing your GitHub repo’s Readme while using the GitHub website is something I do that causes me to have to pull those changes down to my local repo before being able to push new changes to the origin. 

Torre

**Comment by susanBuck** [comment]
Good tips from both @tostaylo and @gboie 👍

I typically see this happen when students make changes to their code directly on Github.com (like in the scenario @tostaylo described).

This point is summarized in the output you received:

> Updates were rejected because the remote contains work that you do not have locally

In this case, remote = the code on Github.com. 

A trick to seeing which commits were done from local vs. done directly on Github.com is to look at the commit history - any commit label as "Verified" was done directly on Github.com.

![image](https://user-images.githubusercontent.com/237711/94448753-4974e400-0179-11eb-9f52-3b7189216244.png)

### How to resolve this...
First, if you're new to Git and if you have significant code changes on your files locally, go ahead and make a backup of your `e28` directory. Sometimes merging can get tricky, and it's always nice to know you have a backup of your latest changes if things go south.

Then, as @tostaylo noted, you'll want to do a `git pull` to sync your latest changes from Github -> local. 

Here's a good run-down on what `git pull` actually does: https://www.atlassian.com/git/tutorials/syncing/git-pull

Summary: it will first pull down any changes, and if there are any changes locally, it will merge it with those changes.

Once the pull is complete, you should then be able to do a `git push` of any commits from local -> Github.

If you get stuck at any point in this process, let us know - as I said - sometimes Git merges can get tricky.

### How to prevent this moving forward...
I recommend _not_ making any changes directly in Github.com, just to avoid merge conflicts. It's best to only make code changes locally and follow a one-way path of local -> github.com -> production.

If you do make changes on Github.com, though, just remember to do a `git pull` locally, that way you can bring everything in sync before making changes.

**Comment by pllealfunes** [comment]
Thank you @gboie , @tostaylo , and @susanBuck. I completely forgot about the changes I made through github.com and since I'm still new to Git I didn't really think of how this could have been an issue later on. I definitely need to read more on Git and pay better attention to what I do. Great lesson, thanks guys 👍
