### ISSUE TITLE
Question about creating your own components

### ISSUE THREAD

**Issue by iamakimmer** [susanBuck/e28-fall20#22]
I went ahead on looking at components, but how can I set data only within the component? If I try to do something like this, I get this error:

https://jsfiddle.net/b2cvxm87/1/

Anyone know how I can resolve this?

**Comment by susanBuck** [comment]
@iamakimmer -

Your syntax for creating/using the component is a little off.

The component template should be separate from the main app template. E.g.:

```html
<!-- One way to define a component template -->
<script type='text/x-template' id='test-component'>
    <div>
       {{ data1 }}
   </div>
</script>


<div id="app">
    <h2>test data:</h2>
    <!-- Here we use the component -->
    <test-component></test-component>
</div>
```

And in the JS, the component needs to be registered as a component using `Vue.component`. E.g.:

```js
const TestComponent = Vue.component('TestComponent', {
  name: 'TestComponent',
  template: '#test-component',
  data() {
    return {     
      data1: 'foo', //data only within this component
    };
  },
});

new Vue({
  el: "#app",
  data() {
  	return {
    
    }
  },
  components: {
    TestComponent: TestComponent,
  }, 

})
```

Side note for anyone else reading this thread - We'll talk about components in Week 6, so don't be alarmed if what we're discussing in this thread seems unfamiliar. : )

**Comment by susanBuck** [comment]
Here's my above example in a JSFiddle: https://jsfiddle.net/xw95aqf4/

**Comment by iamakimmer** [comment]
I did not know "text/x-template" was a thing. Thank you so much!

**Comment by LDubya** [comment]
> I did not know "text/x-template" was a thing. Thank you so much!

I like that so much better than the "JSX"-ish way of embedding HTML inside of a javascript string

**Comment by ColeDCrawford** [comment]
> > I did not know "text/x-template" was a thing. Thank you so much!
> 
> I like that so much better than the "JSX"-ish way of embedding HTML inside of a javascript string

Agreed ... One of the reasons I've struggled / disliked React is the JSX soup that a lot of React components become.

**Comment by LDubya** [comment]
> > > I did not know "text/x-template" was a thing. Thank you so much!
> > 
> > 
> > I like that so much better than the "JSX"-ish way of embedding HTML inside of a javascript string
> 
> Agreed ... One of the reasons I've struggled / disliked React is the JSX soup that a lot of React components become.

It was an instant turnoff for me. I prefer HTML not to be defined inside of a Javascript string. Defining a template inside of an HTML tag like `text/x-template` allows (even if it's a `script` tag), and then referencing that template by ID in the Javascript makes more sense to me.

But I recognize that I'm in the minority on this. Defining HTML inside of a Javascript variable doesn't seem to be a big issue for many developers.

**Comment by susanBuck** [comment]
Some notes on this topic:

+ What the docs say on JSX vs. Templates when comparing Vue and React: https://vuejs.org/v2/guide/comparison.html#HTML-amp-CSS
+ If you're of the school where you like JSX: https://vuejs.org/v2/guide/render-function.html
+ When we get to _Single File Components_ we'll see our components each moved to their own files, with our templates organized amongst the other aspects of the component (JS and CSS)

Example:
```js
<template>
  <p>{{ greeting }} World!</p>
</template>

<script>
module.exports = {
  data: function() {
    return {
      greeting: "Hello"
    };
  }
};
</script>

<style scoped>
p {
  font-size: 2em;
  text-align: center;
}
</style>
```

Going to close this thread, but feel free to keep the discussion going!
