### ISSUE TITLE
Component not rendering inside of element, renders outside of it instead

### ISSUE THREAD

**Issue by LDubya** [susanBuck/e28-fall20#23]
I'm trying to create this **desired outcome**:

```html
<div id="app">
    <table>
        <colgroup>
            <col style="width: 33%;">
            <col style="width: 66%;">
        </colgroup>
        <tbody>
            <tr>
                <td> left 1 </td>
                <td> right 1 </td>
            </tr>
            <tr>
                <td> left 2 </td>
                <td> right 2 </td>
            </tr>
            <tr>
                <td> left 3 </td>
                <td> right 3 </td>
            </tr>
        </tbody>
    </table>
</div>
```

But instead the **actual outcome** is that Vue outputs the  `<tr></tr>` outside of the `<table>` they're defined in:

```html
<div id="app">
    <tr>
        <td> left 1 </td>
        <td> right 1 </td>
    </tr>
    <tr>
        <td> left 2 </td>
        <td> right 2 </td>
    </tr>
    <tr>
        <td> left 3 </td>
        <td> right 3 </td>
    </tr>
    <table>
        <colgroup>
            <col style="width: 33%;">
            <col style="width: 66%;">
        </colgroup>
        <tbody></tbody>
    </table>
</div>
```

**source code**:

```html
<template id="row-component">
    <tr>
        <td>
            {{note.title}}
        </td>
        <td>
            {{note.content}}
        </td>
    </tr>
</template>

<div id='app'>
    <table>
        <colgroup>
            <col style="width: 33%;" />
            <col style="width: 66%;" />
        </colgroup>

        <tbody>
            <row-component v-for='note in notes' :note="note" />
        </tbody>
    </table>
</div>
```

```js
let RowComponent = Vue.component('RowComponent', {
    name: 'RowComponent',
    template: '#row-component',
    props: ['note']
});

let app = new Vue({
    el: '#app',
    data: {
        notes: [{title:"left 1",content:"right 1"},{title:"left 2",content:"right 2"},{title:"left 3",content:"right 3"}]
    },
    components: {
        RowComponent: RowComponent
    }
})
```

This is w/ the development Vue version sourced at: `https://cdn.jsdelivr.net/npm/vue/dist/vue.js`

**Comment by susanBuck** [comment]
You've stumbled on a DOM template parsing caveat relevant to tables. Full explanation here: https://vuejs.org/v2/guide/components.html#DOM-Template-Parsing-Caveats

To address, replace:

```js
<row-component v-for='note in notes' :note="note" />
```

With:
```js
<tr is="row-component" v-for='note in notes' :note="note" />
```

**Comment by LDubya** [comment]
That worked! Thanks 

But I have another question now. The article says that this limitation doesn't apply when using `<script type="text/x-template">`. I wanted to see if that would work, but I get the same bug using `<script type="text/x-template">`.

Maybe I'm misunderstanding what they mean.

**Comment by susanBuck** [comment]
I believe `<script type="text/x-template">` will only do the trick if it's also used on the containing Vue instance.

In this case, the hoisting isn't happening from within your component (which is why changing to `<script type="text/x-template">` didn't fix it), it's happening from the root Vue instance mounted on div#app.

This is just a theory though - I'll follow up on this post this weekend after I get a chance to test it. : )

**Comment by susanBuck** [comment]
Follow-up: 

Ran this test to confirm:
```html
<script type='text/x-template' id='my-table'>
    <table>
        <my-row></my-row>
    </table>
</script>

<script type='text/x-template' id='my-row'>
    <tr><td>Content</td></tr>
</script>
```

Results: The *tr* in *my-row* was *not* hoisted, because it's parent (*my-table*) was a component with its template defined within a `<script type='text/x-template'>`.


![image](https://user-images.githubusercontent.com/237711/95345833-2e952480-0889-11eb-8334-74f4837e7230.png)
