### ISSUE TITLE
Interesting read: Tech problem post-mortems

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-fall20#26]
This repo came across my radar this morning:

https://github.com/danluu/post-mortems

It's a collection of post-mortems of problems tech companies/sites have experienced. 

If you like learning from other's mistakes - or at least not feeling alone when you make your own mistakes - you may enjoy skimming through these. : )

**Comment by tostaylo** [comment]
Very cool! Thank you.

**Comment by gboie** [comment]
Pretty interesting, it would be a good project to create some
visualizations for the stats. I didn't realize that big companies like
Google , Facebook, etc. had serious issues like that. I feel a bit better
about my game breaking when Google Geo API is unable to locate the ISD.

**Comment by estanton900** [comment]
Wow, thank you!

**Comment by ColeDCrawford** [comment]
Thanks, good read!
