### ISSUE TITLE
Permission Denied Installing Vue CLI

### ISSUE THREAD

**Issue by pllealfunes** [susanBuck/e28-fall20#32]
Hey guys, I tried installing vue cli and got a permissions denied error. I used  the line `sudo chown -R $USER /usr/local/lib/node_modules` found in the notes but I still get the following in terminal. Any ideas? Thanks.

`npm ERR! code EACCES`
 
`npm ERR! syscall symlink`

`npm ERR! path ../lib/node_modules/@vue/cli/bin/vue.js`

`npm ERR! dest /usr/local/bin/vue`

`npm ERR! errno -13`

`npm ERR! Error: EACCES: permission denied, symlink '../lib/node_modules/@vue/cli/bin/vue.js' -> '/usr/local/bin/vue'`

`npm ERR!  [OperationalError: EACCES: permission denied, symlink '../lib/node_modules/@vue/cli/bin/vue.js' -> '/usr/local/bin/vue'] {`

`npm ERR!   cause: [Error: EACCES: permission denied, symlink '../lib/node_modules/@vue/cli/bin/vue.js' -> '/usr/local/bin/vue'] {`

`npm ERR!     errno: -13,`

`npm ERR!     code: 'EACCES',`

`npm ERR!     syscall: 'symlink',`

`npm ERR!     path: '../lib/node_modules/@vue/cli/bin/vue.js',`

`npm ERR!     dest: '/usr/local/bin/vue'`

`npm ERR!   },`

`npm ERR!   stack: "Error: EACCES: permission denied, symlink '../lib/node_modules/@vue/cli/bin/vue.js' -> '/usr/local/bin/vue'",`

`npm ERR!   errno: -13,`

`npm ERR!   code: 'EACCES',`

`npm ERR!   syscall: 'symlink',`

`npm ERR!   path: '../lib/node_modules/@vue/cli/bin/vue.js',`

`npm ERR!   dest: '/usr/local/bin/vue'`

`npm ERR! }`

`npm ERR! `

`npm ERR! The operation was rejected by your operating system.`

`npm ERR! It is likely you do not have the permissions to access this file as the current user`

`npm ERR!` 

`npm ERR! If you believe this might be a permissions issue, please double-check the`

`npm ERR! permissions of the file and its containing directories, or try running`

`npm ERR! the command again as root/Administrator.`

`npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pllealfunes/.npm/_logs/2020-10-28T19_26_16_092Z-debug.log`

**Comment by susanBuck** [comment]
Hi @pllealfunes -

If you prefix the install command with sudo, it will run it as an admin and should not hit permission errors:

```
sudo npm install -g @vue/cli
```

**Comment by pllealfunes** [comment]
That worked, thank you so much!
