### ISSUE TITLE
Vue and IE11 experience

### ISSUE THREAD

**Issue by iamakimmer** [susanBuck/e28-fall20#34]
Just thought I'd share some experience with Vue. I deployed my first Vue code on a specific page at work last week. It's not too mission critical, but we do use [logrocket ](https://logrocket.com) to monitor front end errors. I was noticing everyone (.01% of users) on Internet Explorer 11 was failing to see the page and it's because ES6 syntax was not available. Then I had to convert the script file into a backwards compatible JavaScript file using Babel and was able to resolve the compatibility error.

**Comment by susanBuck** [comment]
It's true - Vue (and other modern JS apps) may fail on IE.

You can address this as you did by transpiling to backwards compatible JS, or - another approach to dealing with obsolete browsers is to detect when users enter via them and show them a message like this: https://www.lynda.com/upgrade-browser.

In many cases, when you're dealing with < 1% of a user base, this is the more "economical" way to handle the problem. That being said, if you're in a certain niche industry where you have a higher percentages of IE users, it may not be a viable solution.

All depends on individual circumstances. 

Thanks for sharing this anecdote, @iamakimmer!
