### ISSUE TITLE
cb.apply is not a function

### ISSUE THREAD

**Issue by ColeDCrawford** [susanBuck/e28-fall20#35]
I'm encountering some odd errors with `vue create`, which may be install specific but which I thought I'd post here. Mac OS 10.14.5 Mojave. Node v14.15.0 through nvm (more on this below). npm 6.14.8

When running Vue CLI 4.5.8, I get
```
 WARN  You are using an outdated version of NPM.
there may be unexpected errors during installation.
Please upgrade your NPM version.
```
and then `vue create` crashes:
```
npm ERR! cb.apply is not a function
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/colecrawford/.npm/_logs/2020-11-03T05_10_14_351Z-debug.log
 ERROR  command failed: npm install --loglevel error @vue/cli-plugin-babel@~4.5.0 @vue/cli-plugin-eslint@~4.5.0 @vue/cli-service@~4.5.0 --save-dev
```

When looking at the log file, I see `npm` errors:
```
1 warn npm npm does not support Node.js v14.15.0
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
```

If I switch to `node` v11 with `nvm` (the latest supported release for the version of npm which Vue CLI is detecting), I get the following error (expected), but `vue create` does successfully build:
```
You are using Node v11.15.0.
Node.js 11.x has already reached end-of-life and will not be supported in future major releases.
It's strongly recommended to use an active LTS version instead.
```

The last few `lts` releases (v12.19.0 and v14.15.0) do not work with `vue create`. My `npm` version is 6.14.8 (upgraded using `nvm install-latest-npm`) but Vue is finding `npm@6.2.0` which doesn't understand `node` > v11. While I could keep using node v11, it would be nice to find an actual solution.

This person seems to be having the same problem: [https://stackoverflow.com/questions/63654817/vue-cli-vue-create-namehere-wont-work-with-node-v12-18-3](https://stackoverflow.com/questions/63654817/vue-cli-vue-create-namehere-wont-work-with-node-v12-18-3)

Full debug log attached. It looks like maybe Vue CLI is looking at my system version of `npm` in line 9?

[2020-11-03T05_10_14_351Z-debug.log](https://github.com/susanBuck/e28-fall20/files/5479397/2020-11-03T05_10_14_351Z-debug.log)

**Comment by susanBuck** [comment]
> Vue is finding npm@6.2.0 which doesn't understand node > v11

Can you run `which npm` to see what install of npm your system is using? 

And from that output, run it with `--version` to double check the version.

E.g on my end `which npm` outputs `/usr/local/bin/npm`, and `/usr/local/bin/npm --version` outputs 6.14.8.

**Comment by LDubya** [comment]
if it turns out to be an node version issue, if you have NVM installed, switching between node versions is as simple as ‘nvm use <version>’

**Comment by ColeDCrawford** [comment]
`which npm` gives me `/Users/colecrawford/.nvm/versions/node/v14.9.0/bin/npm`, which is the `npm` from my `NVM` install. Both that path and `npm --version` give me `6.14.8`, which makes sense. But Vue is finding `npm@6.2.0`.

Yeah, switching `node` versions is simple and that's my current workaround, but you still have to reinstall `npm` packages and trying to fix the actual problem rather than just kicking to an old version of Node compatible with the version of `npm` Vue is finding is clunky. I guess I could spin up a Docker container but that isn't an actual solution.

**Comment by susanBuck** [comment]
To summarize what we know so far:

+ When you invoke npm from command line it uses `/Users/colecrawford/.nvm/versions/node/v14.9.0/bin/npm` 
+ But when invoked from Vue CLI it uses `/Users/colecrawford/node_modules/.bin/npm` 

This latter point is gathered from the log file you shared, but you can confirm this by running `vue info` which will output your binaries. 

**Knowing this, the question is: why is Vue CLI using this other NPM instance, and how to do we get it to stop doing that?** 

Can you share the output of `echo $PATH` so we can see what directories your system looks in when looking for executables?

**Comment by ColeDCrawford** [comment]
Interesting, `vue info` is finding the correct version of `npm`:
```
Environment Info:
  System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Edge: Not Found
    Firefox: 78.3.1
    Safari: 13.1.1
  npmGlobalPackages:
    @vue/cli: 4.5.8
```

My `$PATH` is:
`/anaconda3/bin:/Users/colecrawford/.rbenv/shims:/Users/colecrawford/.rbenv/bin:/Users/colecrawford/.nvm/versions/node/v14.15.0/bin:/Users/colecrawford/.composer/vendor/bin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/latest/bin`

Did some more digging though - [this comment in a thread on the issue](https://github.com/nodejs/help/issues/2874#issuecomment-670998288) mentioned having an old `~/node_modules/` directory, which I also had - the only thing in there was `npm`. Removed that, and now I'm up and running fine.

Thanks for the summary! The thread is probably not relevant for most students, but if you've done any prior `node` development (especially with versions < 12) then maybe it will provide some help if you hit this issue.

**Comment by susanBuck** [comment]
Glad it's all sorted out. Invariably edge cases like this pop up every semester, so it's always good to have the data/experience to refer to in future semesters!
