### ISSUE TITLE
Error: Apache won't start

### ISSUE THREAD

**Issue by ARuzek** [susanBuck/e28-fall20#38]
At the end of the video about the e28-api, I opened the xampp control panel to restart apache, but I got this error. 
![first-error](https://user-images.githubusercontent.com/6900736/98186785-1ee31d00-1ed5-11eb-9e29-5e58dba2063d.PNG)

There are some things in the error log, but the latest few from Oct 25 were:
```
[Sun Oct 25 14:08:58.535500 2020] [ssl:warn] [pid 21560:tid 632] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Oct 25 14:08:58.571476 2020] [mpm_winnt:notice] [pid 21560:tid 632] AH00354: Child: Starting 150 worker threads.
``` 
When I tried to quit, I got this error: 
![error](https://user-images.githubusercontent.com/6900736/98186735-083cc600-1ed5-11eb-8cf9-1ae9bce13417.PNG)

**Comment by susanBuck** [comment]
Hi @ARuzek -

My research on the errors you shared indicates this is likely a permissions error.

Try deleting the file at `c:\xampp\xampp-control.ini` (referenced in the error message) and restarting XAMPP. It should generate a new xampp-control.ini file with the correct permissions.

If that doesn't work, let me know and we can explore some other options.

Ref: https://stackoverflow.com/questions/61193574/xampp-mysql-cannot-create-file-xampp-control-ini-access-denied

**Comment by ARuzek** [comment]
That didn't work. I don't get the quitting Application error anymore, but I do still get the Apache shutdown error. I saw something online about Skype blocking the port, but I uninstalled Skype and I still get the error.

**Comment by susanBuck** [comment]
@ARuzek - I will follow-up shortly with more info on how to troubleshoot this - but a quick thought for now:

Because you can't get the e28-api running locally at the moment, just run it on production (details covered in the Part 7 video) and set the axios `baseURL` to point to your production api:

e.g.:
```js
export const axios = require('axios').create({
    baseURL: 'http://e28-api.yourdomain.com',
    responseType: 'json'
})
```

This would at least let you proceed forward with the ZipFoods/ajax communication examples.

**Comment by susanBuck** [comment]
Another quick thing to try is close XAMPP, and re-open it by right clicking and choosing "Run as Administrator". Not a long-term fix, but potential band-aid to get it working.

**Comment by susanBuck** [comment]
Revisiting this thread now that I have more time to look at it.

If Apache is still failing to start, can you run through the troubleshooting steps described here: https://hesweb.dev/e28/notes/local-server/xampp-windows#port-conflict

**Comment by susanBuck** [comment]
Hi @ARuzek - Just checking in to see if you were able to resolve this issue. Let me know if there's anything else I can do to assist.

**Comment by ARuzek** [comment]
@susanBuck It wasn't a port conflict. I just ended up using the production version. It was a little bit of extra time, but not too bad at all.  Thank you

**Comment by susanBuck** [comment]
Ok - will close this thread out then.

If you end up wanting to debug things locally, drop me an email me and we can set up a time to connect via Zoom and troubleshoot in real time. 👍
