### ISSUE TITLE
Tip: setup local e28-api and error "Permission denied" on Mac system

### ISSUE THREAD

**Issue by adejeffchen** [susanBuck/e28-fall20#39]
After running the command "bash setup" within htdocs/e28/e28-api, I saw the following

```
===> Laravel initial setup
Local: Setting write permissions on directories that Apache needs write access to
chmod: /core/database: No such file or directory
chmod: /core/storage: No such file or directory
chmod: /core/bootstrap/cache: No such file or directory
chmod: /core/database/migrations/: No such file or directory
chmod: /core/database/factories/GeneratedModels: No such file or directory
chmod: /core/app/Models/GeneratedModels/: No such file or directory
chmod: /core/app/Http/Controllers/GeneratedControllers/: No such file or directory
chmod: /core/app/Http/Requests/GeneratedRequests/: No such file or directory
chmod: /core/database/factories/GeneratedModels: No such file or directory
chmod: /core/routes: No such file or directory
Creating environment file (.env)
Generating app key
Application key set successfully.
```

After host setup and when I go to http://e28-api.loc/, I see the following error

> UnexpectedValueException
> The stream or file "/Applications/XAMPP/xamppfiles/htdocs/e28/e28-api/core/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

Running the following cmd solves the problem for me
$ chmod -R 777 ./core/

**Comment by susanBuck** [comment]
Thanks for posting about this, @adejeffchen -

Can you share the output you see from the setup script under the section "===> Detecting system" ?

It looks like it's not identifying the correct path to your `core/` directory.

(Your solution of manually fixing the permissions gets the job done, but I'd like to sort out the underlying issue of why the setup script isn't successfully setting the permissions).

**Comment by adejeffchen** [comment]
Here they are. 
```
===> Detecting system
setup: line 31: realpath: command not found
* Setup script version: 1.0.0
* Server: local
* PHP executable: /Applications/XAMPP/xamppfiles/bin/php
* API directory: /
* Core directory: /core/
* Public directory: /core/public/
```

and..
```
$ realpath
-bash: realpath: command not found
```

**Comment by susanBuck** [comment]
Ok, that's helpful - it looks like a command (`realpath`) I'm using to detect where the setup script is being run from is not available on your system, so it's failing to resolve the correct path to `/core`.

I'm going to look into a more universal command I can use instead and will update the setup script accordingly.

**Comment by susanBuck** [comment]
I changed approaches with how it's resolving paths so `realpath` is no longer used.

You can update your setup script to reflect these changes by copying the source from here: https://raw.githubusercontent.com/susanBuck/e28-api/master/setup

In order to test that it's working on your end, can you first remove the core directory (`rm -rf core`), and then re-run the `bash setup` command?

It's necessary to remove `core` because the permission step will only be executed on the very first run of the setup script, before the `/core` directory exists.

(Thanks in advance for helping me test this fix!)

**Comment by adejeffchen** [comment]
The new setup works! no chmod needed after. 

and path looks good
```
===> Detecting system
* Setup script version: 1.0.1
* Server: local
* PHP executable: /Applications/XAMPP/xamppfiles/bin/php
* API directory: /Applications/XAMPP/xamppfiles/htdocs/e28/e28-api/
* Core directory: /Applications/XAMPP/xamppfiles/htdocs/e28/e28-api/core/
* Public directory: /Applications/XAMPP/xamppfiles/htdocs/e28/e28-api/core/public/
```
