### ISSUE TITLE
Canvas Image Attachment Not Visible?

### ISSUE THREAD

**Issue by christian-hilton** [susanBuck/e28-fall20#4]
Hi, is it expected behavior to see this "?" image preview when attaching screenshots to Canvas?  Or does that mean Canvas failed with my image?  [I would have just verified after submitting, if this was possible]

Please let me know, thanks!
- Christian

![Screen Shot 2020-09-02 at 7 22 12 PM](https://user-images.githubusercontent.com/52005307/92064241-f3677900-ed51-11ea-9f5a-b442282fa0f7.png)

**Comment by kalbfled** [comment]
The image appeared for me.  Are you blocking any scripts with a browser extension, such as NoScript?

**Comment by susanBuck** [comment]
It's not expected behavior - you should see your image. If you try uploading a different image (just as a test), does that show?

**Comment by christian-hilton** [comment]
It was a consistent issue with Safari (despite no browser extensions), but worked using Chrome.  Resolved now, thanks!

**Comment by susanBuck** [comment]
Glad you got it sorted out! I'll drop a note with Canvas support to report the issue.
