### ISSUE TITLE
Component Macro

### ISSUE THREAD

**Issue by gboie** [susanBuck/e28-fall20#41]
How can we enable some of these cool Vue macros for Visual Studio Code?

**Comment by susanBuck** [comment]
The macros you see me use in lecture are run by [atext](https://www.trankynam.com/atext/), a Mac macro program. (There are lots of similar programs for Windows if that's your OS)

Alternatively, you can create macros directly in VSCode using their "Snippets" feature.

Learn about snippets here: 
https://code.visualstudio.com/docs/editor/userdefinedsnippets

Learn how to make your own snippets here: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets

Let me know if you have any follow-up questions about the above.

**Comment by gboie** [comment]
Great, thank you! I am on a Chromebook as an experiment, I guess I will
have to rely on VSCode snippets.

Thanks,
Gabriel

**Comment by susanBuck** [comment]
I should also mention the [Vetur plugin we use](https://hesweb.dev/e28/notes/vue/single-file-components#vetur-vue-tooling-for-vs-code) has a bunch of Vue snippets built-in. Ref: https://vuejs.github.io/vetur/snippet.html#customizable-scaffold-snippets
