### ISSUE TITLE
Error: Cannot Read Property Name of Null

### ISSUE THREAD

**Issue by pllealfunes** [susanBuck/e28-fall20#44]
Hi guys, 

I started working on p2, a recipes app, and I keep get the following error when I want to see more info of a single recipe. I have a ShowRecipes component (read all recipes) and a ShowRecipe component (read one recipe). I'm not sure where I'm going wrong, any help? Thanks!

`[Vue warn]: Error in render: "TypeError: Cannot read property 'name' of null"
found in
---> <ShowRecipe> at src/components/ShowRecipe.vue
       <App> at src/App.vue
         <Root>`

## ShowRecipes Component
<img width="518" alt="Screen Shot 2020-11-06 at 6 07 46 PM" src="https://user-images.githubusercontent.com/51715816/98422947-1c123480-205b-11eb-8236-23711b25c691.png">

## ShowRecipe Component
<img width="463" alt="Screen Shot 2020-11-06 at 6 10 18 PM" src="https://user-images.githubusercontent.com/51715816/98423016-5c71b280-205b-11eb-979d-c6cc72c055e2.png">

**Comment by susanBuck** [comment]
Hi @pllealfunes - You'll want to add a `v-if="recipe"` to the div surrounding the recipe so it only tries to render that data once the recipe is available (after mounted executes):

![image](https://user-images.githubusercontent.com/237711/98425766-5e8c3f00-2064-11eb-80fb-9f6383785ccd.png)

**Comment by pllealfunes** [comment]
It worked, thank you!
