### ISSUE TITLE
Created vs Computed for Zip Foods

### ISSUE THREAD

**Issue by aeg224** [susanBuck/e28-fall20#45]
When implementing last week's ZipFoods exercise, I used the 'created' property to call a method that retrieves the product data by ID (code below). As a result, the bug that prevented product pages from displaying on refresh (detailed in week 10 pt4) was not present in my application. 

Is the 'created' approach as good as the 'computed' approach? I did consider using the computed method, but did not because I figured it would require more computing power (especially if there were multiple instance of the variable on the same page). Is this accurate?

```        
...
created: function(){
            this.getInfo();
        },
        methods: {
            getInfo(){
                    this.products.forEach(this.processData)
            },
            processData(item){     
                    if (this.id == item.id){
                        this.productName=item.name;
                        this.productDescription=item.description;
                        this.productPrice=item.price;
            }
...
```

**Comment by aeg224** [comment]
After looking at it closely, it looks like the bug was not occurring for a different reason, so I'm going to close the issue.

**Comment by susanBuck** [comment]
I know this issue is resolved, but just wanted to weigh in on this question:

> I did consider using the computed method, but did not because I figured it would require more computing power (especially if there were multiple instance of the variable on the same page)

Vue does a lot of intelligent caching, so computed property are only re-evaluate as needed. 

I'd say deciding between a computed property and a lifecycle hook isn't so much a performance question - they just serve different purposes.
