### ISSUE TITLE
Issues with Update Capability in P2

### ISSUE THREAD

**Issue by pllealfunes** [susanBuck/e28-fall20#48]
Hi @susanBuck,

I'm trying to add the option to update a recipe in my project but I keep running into the following errors. 

The first issue I have is when I refresh the edit page I get the ` Error in render: "TypeError: Cannot read property 'id' of undefined"` and I don't know why. 

The second issue has to do with the checkbox that indicates whether or not a recipe is considered a favorite. I have Favorite set as a boolean in my e28-api resources.json and when you see a single recipe you can see whether or not if it's a Favorite. However, when I go to the edit recipe page the checkbox is always checked if I have a v-model of recipe.favorite attached to it. How can I make sure the checkbox is only checked when it is a favorite and have the ability to uncheck it if I decide the recipe is no longer a favorite?

**Comment by susanBuck** [comment]
Hi @pllealfunes -

The first issue is coming from the router-link in EditPage.vue:

```html
<router-link id="previous" :to="'/recipe/' + recipe.id">Back to Recipe</router-link>
```

This is happening because on initial page load, we have to wait for the ajax call to finish getting the recipe info.
This includes when you refresh the page and you're already on the edit page.

You don't see the error if you start somewhere else and then navigate to the edit page, because the recipes will have already been loaded when App.vue was mounted.

To fix this, add a `v-if="recipe"` to your router link so it will only render once the recipe is available (similar to how you did in the *addRecipe* div.

Looking into your second question now and will reply to that shortly...

**Comment by susanBuck** [comment]
**re: The favorite checkbox:**

To understand what is going on here, note that any of the data we get back from the API is always going to be a string.

![image](https://user-images.githubusercontent.com/237711/98878816-e8b41900-2451-11eb-805c-8d7795e7071c.png)

This is true even for our non-string fields, such as our numeric fields and boolean fields.

So when the API gives us the value for favorite, we're not getting it as an actual boolean value, instead we're getting it as a string of either "1" or "0". And string values in JavaScript will always evaluate to true.

So if you have a recipe that is _not_ a favorite, that comes in as a string "0" which actually equates to true.
And likewise for a recipe that _is_ a favorite - its value is a string "1" which equates to true.

The end result is the checkbox always gets checked.

There are a couple ways to address this.

**Option 1)**
When loading the recipes in App.vue, convert the *favorite* value to a boolean value:

```js
updateRecipes() {
    axios.get('recipe').then((response) => {
        // Iterate through each recipe,
        // casting its `favorite` value from a string "1"/"0" to true/false boolean
        response.data.recipe.forEach((recipe) => {
            recipe.favorite = Boolean(Number(recipe.favorite));
        });

        this.recipes = response.data.recipe;
    });
},
```

*Edit: This code was originally incorrect as it was trying to edit all the favorite values at once. It now correctly iterates through the recipes to edit the favorite values individually.*

**Option 2)**
[Vue has the option explicitly set the true/false value for a checkbox using the attributes *true-value* and *false-value*.](https://vuejs.org/v2/guide/forms.html#Checkbox-1)

Knowing this, you could set the _true-value_ to _"1"_ and the _false-value_ to _"0"_, bringing it in sync with the string data you're getting from the API.

```html
<input
                    type="checkbox"
                    id="favorite"
                    true-value="1"
                    false-value="0"
                    v-model="recipe.favorite"
                />{{ recipe.favorite }}
```

In my tests, both of the above techniques got the job done, but let me know if you run into any issues implementing them on your end.

**Comment by pllealfunes** [comment]
I tried following all of your suggestions but for the issue on refresh I had to add the `v-if="recipe"` to my very first div ` <div v-if="recipe" id="create-page">` in order for it to work because I would still get errors in the console when I added it to the router link.

As for the checkbox, option 2 worked but when I tried out option 1 the checkbox still shows to be checked even when it's not supposed to.

**Comment by susanBuck** [comment]
**re: v-if=recipe not working when applied to the router link**
That's odd. Double checked and applying it to the router link works on my end. Would you mind moving it back to the router-link and confirming you get the error on refresh, then updating your repo with this code? That way I can clone on my end and test it _exactly_ as you're seeing it. 

**re: Option 2 checkbox solution not working**

My mistake on this one - the code should iterate through _each_ of the recipes and cast the favorite value to a boolean. The original sample I provided was wrong. It should be:

```js
updateRecipes() {
    axios.get('recipe').then((response) => {
        // Iterate through each recipe,
        // casting its `favorite` value from a string "1"/"0" to true/false boolean
        response.data.recipe.forEach((recipe) => {
            recipe.favorite = Boolean(Number(recipe.favorite));
        });

        this.recipes = response.data.recipe;
    });
},
```

**Comment by pllealfunes** [comment]
Thank you for the updated code. I tried it out and it works :)

I did move the v-if back to the router link and still get the errors `Error in render: "TypeError: Cannot read property 'favorite' of undefined"`. I have also updated my repo and added a screenshot.


<img width="1440" alt="Screen Shot 2020-11-12 at 1 27 32 PM" src="https://user-images.githubusercontent.com/51715816/98980704-f79ada00-24ea-11eb-8920-344ee957b5cc.png">

**Comment by susanBuck** [comment]
Ok, cool - just pulled down the latest changes.

It is producing an error, but it's different from the first error you noted, which was:

> Error in render: "TypeError: Cannot read property 'id' of undefined"

Adding `v-if="recipe"` to the router link fixed that error.

This new error is:

> "TypeError: Cannot read property 'favorite' of undefined

This is happening because it looks like you removed the `v-if="recipe"` from `<div id="addRecipe">`.

**Any element that is trying to access recipe data, needs to only be rendered _if_ recipe is available.**

You can address this on an element by element basis, e.g. add it to the router link and the `<div id="addRecipe">`...

 _Or_, as you noted above, if you just add it to the most parent div that encompasses everything (`<div v-if="recipe" id="create-page">`) then you won't run into any problems.

**Comment by pllealfunes** [comment]
Oh my goodness, I didn't even notice that I removed the v-if from the addRecipe div! I also forgot to mention it was a new error. I'm so sorry for the confusion... thank you so much for your responses =)

**Comment by susanBuck** [comment]
No problem! Glad it's all sorted out. :-)
