### ISSUE TITLE
How to Change Your Terminal Colors

### ISSUE THREAD

**Issue by ARuzek** [susanBuck/e28-fall20#5]
The first time I used a terminal, I was scared. Changing the colors can help make it seem less scary. So if anyone is using terminal for the first time, here's how you can customize the colors. 

Terminal > Preferences > Profiles

 ![Pretty Terminal](https://user-images.githubusercontent.com/6900736/92248365-2ca50380-ee8e-11ea-956a-73bd96a9ec78.png)

On Command Prompt for Windows: You right click the top bar and then select Properties > Colors

On Cmder for Windows: You right click the top bar and then select a scheme/theme or Settings > Features > Colors to customize

**Comment by susanBuck** [comment]
Amazing the difference a good color scheme can make. Thanks for sharing this tip, @ARuzek. : )

**Comment by Ashley877** [comment]
Thank you for sharing! Now the hard part is to decide what theme I like the best!

**Comment by vmorris412** [comment]
Thank you, @ARuzek! It's always nice to work in an environment that we find easy on the eyes!

**Comment by ColeDCrawford** [comment]
Everyone has different preferences too ... I usually go for dark themes to reduce eye strain. Don't think I could do the lavender!
