### ISSUE TITLE
Changing an object in an array and it's rendering on a page

### ISSUE THREAD

**Issue by iamakimmer** [susanBuck/e28-fall20#51]
If I have an list full of objects, and update one of the objects and it's properties, it doesn't seem to reflect the change in the rendering of where I have a v-for loop. Is this the nature of reactivity in Vue?

**Comment by susanBuck** [comment]
In theory, it should update it. Do you have an example on Github I can recreate/test?

**Comment by iamakimmer** [comment]
https://github.com/iamakimmer/e28

You'll have to do a bash set up on my api : https://github.com/iamakimmer/e28/tree/master/e28-api

It may be confusing to follow the code, but you can hover over any line, and you will see a microphone button come up. Hold down the button and you can record yourself speaking the line. Unpress the button and it will save the audio file and save the line's audio file URL to the database. 

Function updateLine is called as soon as you depress the button and it saves the audio file:

```        updateLine(line, url, currentLineIndex) {
            console.log('updating line', line, url);
            line.audio_file = url;
            console.log('line', line);
            axios.put(`/line/${line.id}`, line).then((response) => {
                console.log('response', response);       
                console.log('lines', this.lines);  
                console.log('currentLineIndex', currentLineIndex);                       
                this.$set(this.lines, currentLineIndex, line); //if u comment this line the line wont update in the array
            });            
            axios.get('line/query', {
                params: {
                    script_id: this.scriptId,
                }
            }).then((response) => {
                this.lines = response.data.results;
            });             
        },
```

This is where I update the line's audio_file URL:

```           
 line.audio_file = URL;
``` 

If I uncomment this, 
```
                this.$set(this.lines, currentLineIndex, line); 
```
Clicking the line no longer plays the audio file because it appears it's not set

**Comment by susanBuck** [comment]
Hi @iamakimmer -

Thanks for sharing more context. 

Before you discovered that using *this.$set* worked, how were you trying to update the lines?

Recall that if you update an array/object using a mutation method (push, pop, shift, etc.), Vue is able to "listen" for these changes and trigger the reactivity system to update the DOM. 

Other mutation approaches, however, may not trigger the reactivity system. For example, square bracket syntax would not:

```js
this.lines[0] = newLine; // This would not trigger the reactivity system
```

As an alternative to using a mutation method (push, pop, shift, etc.), you can use [Vue.set](https://vuejs.org/v2/api/#Vue-set) (as you discovered) to force the reactivity system to detect the change.

Ref:
+ https://hesweb.dev/e28/notes/vue/list-rendering#reactivity-and-mutating-arraysobjects
+ https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

Going back to your original question:

> If I have an list full of objects, and update one of the objects and it's properties, it doesn't seem to reflect the change in the rendering of where I have a v-for loop. Is this the nature of reactivity in Vue?

My answer of *"In theory, it should update it."* should have actually been *"it depends on *how* you're updating it"* : )

**Comment by iamakimmer** [comment]
Ah that makes sense. Thank you!
