### ISSUE TITLE
Build process hangs

### ISSUE THREAD

**Issue by LDubya** [susanBuck/e28-fall20#54]
I'm using HighCharts for some data viz, which is core functionality. They provide a bunch of useful assets, such as this vector dictionary of US counties: (warning, slightly larger text file)

https://code.highcharts.com/mapdata/countries/us/us-all-all.js

I have that file saved as a JS file locally (src/us-all-all.js). I have my version modified to `export` the top-level variable instead of the way they have it now where it tries to modify a global variable that it expects to exist, so I definitely need this code committed. 

So instead of `Highcharts.maps["countries/us/us-all-all"] = {...}`, it's `export const usAllAll = {...}`

I then `import` the file into the three components that are using it.

This works fine during dev, but when I go to build using `npm run build`, the console outputs ...

```
Building for production...[BABEL] Note: The code generator has deoptimised the styling of /Applications/XAMPP/xamppfiles/htdocs/e28/project2/src/us-all-all.js as it exceeds the max of 500KB.
```

And then hangs. After a few minutes computer starts to overheat.

Google didn't help much 😅 

FWIW, I could build before. So I think it's just that file that's making the difference. The file is already super minified, so I don't think it even needs to be cleaned up, if that can be avoided. But maybe the build process is hanging because it's trying to compile that file together with the rest of the external JS. 

Any ideas how to successfully build?

**Comment by tostaylo** [comment]
Have you tried  modifying your Babel config  to use the “compact” option described here https://stackoverflow.com/questions/29576341/what-does-the-code-generator-has-deoptimised-the-styling-of-some-file-as-it-e ?

**Comment by LDubya** [comment]
@tostaylo I ran into that, but wasn't sure about what it would be doing under the hood. I was worried that it would be applied globally to the rest of the files and result in the final build not being as compact as it could be.

But it does build:

```
module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset'
  ],
  "compact" : false
}

```

I'll go with it for now.

Wonder if there are any major side-effects though

**Comment by tostaylo** [comment]
Good concern.  I’m wondering if you can import the large file using dynamic imports with webpack so it is its own chunk of code and not included in the main bundle. Then in the Babel config only apply the “compact :false ” option on that particular chunk of code associated with the large file and not the main bundle. I’m not sure if Babel allows for that level of configuration for this particular option but may be worth looking into.

**Comment by LDubya** [comment]
Something to look into. Thanks for the cluch assist, @tostaylo 💪
