### ISSUE TITLE
Error: Property or method "recipe" is not defined on the instance but referenced during render.

### ISSUE THREAD

**Issue by krishb09** [susanBuck/e28-fall20#55]
Hi everyone, 

I have been running into an issue for rendering my Favorites Page on the recipe app I'm working on. When the user clicks the 'Add to Favorites' button I want that recipe to get sent back to my database and populate on the Favorites Page. 

It would look similar to my 'Recipes Page' where all the recipes are populated initially. But, for some reason the 'recipe' object is undefined and I can't see why this would be the case. 

If anyone might know what the issue is- would really appreciate the help! 

here's my github: https://github.com/krishb09/e28

![Screen Shot 2020-11-17 at 11 11 18 AM](https://user-images.githubusercontent.com/50959163/99415282-a3667000-28c5-11eb-86c3-47bc462a9f70.png)

![Screen Shot 2020-11-16 at 11 26 32 PM](https://user-images.githubusercontent.com/50959163/99415473-d3157800-28c5-11eb-8e85-79287ea3597b.png)

**Comment by susanBuck** [comment]
Hi @krishb09 -

The issue is coming from line 10 in *FavoritesPage* where it's trying to access a `recipe.id` to display the image:

```html
<img
              :src="require('@/assets/images/' + recipe.id + '.png')"
              alt="Image"
              class="rounded-0"
            />
```

At this point in the code, `recipe` is not defined - it only exists later within the context of the *router-link v-for*.

Wondering if you even need this image there? It seems like you only need the images in the *router-link v-for* to display the image for each favorite.

**Comment by krishb09** [comment]
Hi @susanBuck , that makes sense, I didn't realize that it wasn't available till the router-link later on. And good point, I don't need that image there. 

Another issue I am having- when I click the 'add to favorites' button- the networks tab doesn't show a post request being made and I am instead getting a "GET" request error.  There seems to be a lag in the request?

![Screen Shot 2020-11-17 at 12 02 37 PM](https://user-images.githubusercontent.com/50959163/99422189-479fe500-28cd-11eb-87a0-0ffb0437dca2.png)

![Screen Shot 2020-11-17 at 12 03 00 PM](https://user-images.githubusercontent.com/50959163/99423140-43c09280-28ce-11eb-92e7-2285663ddada.png)

**Comment by susanBuck** [comment]
@krishb09 - Interesting - "Add to favorites" is working on my end.

The errors you're getting in the console don't seem specific to your app code, but the behind the scenes stuff happening with the webpack dev server.

Can you try stopping the server and then starting it again (`npm run serve`)?

**Comment by krishb09** [comment]
Oh yep re-starting the server helped, thank you!

**Comment by susanBuck** [comment]
Excellent! Going to close out this thread but feel free to start a new one if you face additional road blocks.
