### ISSUE TITLE
Undefined recipe being sent back from api

### ISSUE THREAD

**Issue by krishb09** [susanBuck/e28-fall20#56]
I am running into another issue where the recipe is being returned as undefined from the API. 
Here, I tried to console.log out 'response.data.recipe' but got back undefined. 

And there is also an issue of 'the recipe id field is required' and I think these 2 issues might be related ?

![Screen Shot 2020-11-17 at 2 45 04 PM](https://user-images.githubusercontent.com/50959163/99439769-a1130e80-28e3-11eb-928c-5986257e07ce.png)
![Screen Shot 2020-11-17 at 2 43 20 PM](https://user-images.githubusercontent.com/50959163/99439772-a2dcd200-28e3-11eb-89e7-f10d9d341c51.png)

**Comment by susanBuck** [comment]
Hi @krishb09 - Can you push your latest code changes to Github? The current version of your app I have locally is not showing this error.

**Comment by krishb09** [comment]
https://github.com/krishb09/e28/tree/master/p2  oh oops, should be all updated now

**Comment by susanBuck** [comment]
Thanks!

Zooming in on code that is attempting to add the favorite:

```js
axios.post('/favorite', this.recipe).then((response) => {
                console.log(response.data);
                if (response.data.errors) {
                    this.errors = response.data.errors;
                } else {
                    this.$emit('update-recipes');
                    this.showConfirmationMessage = true;
                }
            });
```

What this code is doing is trying to post the data for `this.recipe` to */favorite*. 

The data for a recipe includes several things: *description, directions, ingredients, name, etc*.

But the data for a "favorite" is only expecting one thing - a *recipe_id*: 

![image](https://user-images.githubusercontent.com/237711/99450631-fdc7f680-28ee-11eb-9540-2286e61d04e0.png)

This explains why the response you were receiving in return included a validation error saying *The recipe id field is required*.

To fix this, you can amend your axios post to look something like this:

```js
addFavoriteRecipe() {
            axios
                .post('/favorite', { recipe_id: this.recipe.id })
                .then((response) => {
                    // ... code redacted for previty
                });
        }
```

The key part here is the second param we pass to *post* which is the data we're posting:

```
{ recipe_id: this.recipe.id }
```


When I tested that, I got a successful response and was able to confirm the new row was added in the API.

**Comment by krishb09** [comment]
ohh okay I see what you mean, thank you so much!
