### ISSUE TITLE
Project 2: Do we need to setup and use RESTful API?

### ISSUE THREAD

**Issue by gboie** [susanBuck/e28-fall20#57]
Do we need to setup a RESTful API for Project2? 
If yes, any clever ways to use Vue Router for it?
If no, can we use the  localstorage (https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) for persistence? Or simple file storage?

Thank you,
Gabriel

**Comment by susanBuck** [comment]
Per the [p2 specs](https://hesweb.dev/e28/projects/2):

> Some data must be retrieved from and persisted to the server; updating existing data is optional

You can use the e28-api I provided to do this, or set up your own server if you prefer. The point is to demonstrate communicating with a server via axios/ajax.

Thus, you can't substitute local storage or file storage for this.

**Comment by gboie** [comment]
Got it, thank you! I was trying to build the API within the same project using routes within vue-router, is that a good idea, or should I have a separate application for it?

**Comment by susanBuck** [comment]
If you mock an API as using Vue/routes, you wouldn't have the permanent/secure storage you get with a database/server-based API. 

On that note, I should amend my previous reply: I shouldn't say you can't use file storage (vs. database storage), as that can be used as permanent/secure storage on a server. 

I stand by local storage not being a substitute though.

Maybe you can speak a bit to your motivation here - is there a particular reason you don't want to use a RESTful API? (Understanding this better might push me to be make some exceptions in the specs on a case-by-case basis. : )

**Comment by gboie** [comment]
I am all about APIs, I am running a bit behind here and wanted to know what is the exact requirement to ensure compliance.

**Comment by susanBuck** [comment]
Gotcha! 

To be honest, I think rather than re-inventing the wheel with some sort of mock Vue-based API, it'd be most efficient to just use the API I provide. Follow the few steps to get it set up, plug in your own resources, and you can just start using it. 

Closing this thread out, but don't hesitate to let me know if you have any other questions.

**Comment by gboie** [comment]
I wrote this article ages ago, when sails js was in beta, on how to create an API in 2 minutes or less, will try that, since it should only take 2 minutes first :)

**Comment by susanBuck** [comment]
Go for it! : )

Curious to read the article - don't see a link in your post though?

**Comment by gboie** [comment]
So my article is obsolete, it almost doesn't make sense, but it was much easier then. This is the new article I follow, I actually have to edit js files, which was not the case in the past: https://medium.com/@Grigorkh/rapid-rest-api-development-with-sails-js-ea5a25606223. My old article here:https://www.blogger.com/blog/post/edit/preview/5059294697396226067/2482715813445385988

**Comment by gboie** [comment]
Silly question, is this assignment due at midnight? Thank you

**Comment by susanBuck** [comment]
By midnight.

![image](https://user-images.githubusercontent.com/237711/99459491-31f5e400-28fc-11eb-8617-4dacf66caab9.png)

**Comment by gboie** [comment]
Perfect, thank you!
