### ISSUE TITLE
Permissions for Peer Review sheet

### ISSUE THREAD

**Issue by tostaylo** [susanBuck/e28-fall20#58]
I am unable to input my github repository URL on the peer review sheet. https://docs.google.com/spreadsheets/d/1f9v4sao-9QmqkUt690Trdr_wh3pJH1_3FrYNlV72Sqo/edit#gid=0 is the link I am following. ```You are trying to edit a protected cell or object. Please contact the spreadsheet owner to remove protection if you need to edit.``` is the message I receive.  I've tried to use the sheet with different Google accounts with the same result.

**Comment by susanBuck** [comment]
Just fixed the permissions - thanks for the head's up.
