### ISSUE TITLE
Local Domains not being found on MacOS

### ISSUE THREAD

**Issue by sneadthaman** [susanBuck/e28-fall20#59]
I am able to view http://practice.loc, which is pointing to 127.0.0.1, but I'm not able to open any of my virtual hosts in a browser. I have my apache config file setup to Include Virtual Hosts and my vhost file entry is a copy of the output from 'bash setup'. I have a feeling there is a permissions issue somewhere but I'm unable to resolve this on my own. 

Does anyone have any ideas?

**Comment by susanBuck** [comment]
Hi @sneadthaman -

1. Can you share the contents of your Virtual Hosts config file?

2. There is a command you can run to confirm your Virtual Host config file does not have any errors - see details here: https://hesweb.dev/e28/notes/local-server/local-domains#troubleshooting

3. Can you confirm you restarted Apache after editing your Virtual Host config file?

3. Can you confirm you have the domain(s) you're setting up [mapped to 127.0.0.1 in your computer's host file](https://hesweb.dev/e28/notes/local-server/local-domains#step-3-create-a-new-host)?

3. Can you share a screenshot/info on what error you see in the browser for a domains that isn't working.

**Comment by sneadthaman** [comment]
# Virtual Host Config
```
<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs
    <Directory /Applications/XAMPP/xamppfiles/htdocs>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName e28-api.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e28_new/e28-api/core/public/
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e28_new/e28-api/core/public/>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName e28p1.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e28_new/p1/
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e28_new/p1/>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>
```
I've restarted Apache many times

# /etc/hosts
```
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
127.0.0.1       practice.loc
```

<img width="1344" alt="Screen Shot 2020-11-18 at 4 30 22 PM" src="https://user-images.githubusercontent.com/30006142/99590673-aa6faa00-29bb-11eb-927c-8e5e8b9315cc.png">

**Comment by susanBuck** [comment]
I don't see a line mapping `e28-api.loc` to `127.0.0.1` in the hosts file contents you shared.

Should see something like this:

```
127.0.0.1 e28-api.loc
```

Also, when accessing it in the browser, you can exclude `www` - should just be `http://e28-api.loc`.

**Comment by sneadthaman** [comment]
omg


Thank you!!

**Comment by susanBuck** [comment]
np! : )
