### ISSUE TITLE
Windows XAMPP installation - Network resource unavailable

### ISSUE THREAD

**Issue by sandeepandatta** [susanBuck/e28-fall20#6]
Hi , when i am trying to install XAMPP , i am getting the following error.Kindly let me know the way forward

![image](https://user-images.githubusercontent.com/66510275/92299069-d8913200-ef14-11ea-818a-3c2d9f9ef274.png)

**Comment by sandeepandatta** [comment]
Ok. solved it Found the solution in apache website. Thanks

![image](https://user-images.githubusercontent.com/66510275/92301307-4e52c900-ef28-11ea-8478-51166da3ce43.png)

**Comment by susanBuck** [comment]
Glad you got it sorted out and thank you for sharing your solution @sandeepandatta!
