### ISSUE TITLE
Will week 14 lecture cover authentication as well?

### ISSUE THREAD

**Issue by adejeffchen** [susanBuck/e28-fall20#60]
Currently, week 14's topics are

> Validation
> Testing
> Static site hosting
> Vue.js vs. other frameworks

Will we also go over authentication related topics (register, login, logout, API that requires auth)? 

Thanks

**Comment by susanBuck** [comment]
@adejeffchen - Yup - it will be either week 14, or week 15, or split out over the two. This semester got a little jumbled at the end with the addition of Vue 3/composition API stuff so I'm not positive yet which week I'll put in the auth material. Will make a note to reflect this on the schedule!

**Comment by susanBuck** [comment]
Updated so that Week 14 and 15 tentatively looks like this:


**Week 14 - Tue Dec 1**
+ Authentication
+ Validation
+ Testing

**Week 15 - Tue Dec 8**
+ Composition API
+ Vue.js vs. other frameworks
+ Static site hosting
+ Complete Project 3

**Comment by adejeffchen** [comment]
Thank you!
