### ISSUE TITLE
e28-api bash setup issue

### ISSUE THREAD

**Issue by balkasem** [susanBuck/e28-fall20#61]
hi all,

im getting this error when trying to run the batch setup command, any idea why?

<img width="949" alt="Screen Shot 2020-11-24 at 11 20 28 AM" src="https://user-images.githubusercontent.com/15233956/100122383-4f203a80-2e47-11eb-92a6-b66f472c3865.png">

**Comment by balkasem** [comment]
@susanBuck would appreciate your help please

**Comment by susanBuck** [comment]
It's failing at the step where it's attempting to clone the api core from Github.

Do you have a SSH key set up between your computer and Github? (ref: [Github setup](https://hesweb.dev/e28/notes/git/github))

You can confirm if you do by running this command:

```
ssh -T git@github.com
```

If it's successful, it should return:

```
Hi [your username]! You've successfully authenticated, but GitHub does not provide shell access.
```

**Comment by balkasem** [comment]
it's giving me : 

git@github.com: Permission denied (publickey).

**Comment by susanBuck** [comment]
That means you do not have a SSH key set up between your computer and Github. Follow the steps in the notes I linked above to set this up.

**Comment by balkasem** [comment]
@susanBuck having difficulty connecting to the API, please advise

<img width="1440" alt="Screen Shot 2020-11-24 at 1 53 41 PM" src="https://user-images.githubusercontent.com/15233956/100139135-03788b80-2e5d-11eb-8848-7c90b2725289.png">

<img width="1440" alt="Screen Shot 2020-11-24 at 1 56 15 PM" src="https://user-images.githubusercontent.com/15233956/100139141-04a9b880-2e5d-11eb-94a5-d40d6be245c3.png">

**Comment by balkasem** [comment]
<img width="1440" alt="Screen Shot 2020-11-24 at 2 09 23 PM" src="https://user-images.githubusercontent.com/15233956/100140338-d2995600-2e5e-11eb-8248-ec4f34c09292.png">

**Comment by balkasem** [comment]
i seem to have resolved it now @susanBuck :)

**Comment by susanBuck** [comment]
@balkasem - Glad to hear it - let me know if you have any other follow-up questions.
