### ISSUE TITLE
Getting Access denied on SSH root

### ISSUE THREAD

**Issue by balkasem** [susanBuck/e28-fall20#62]
I'm having difficulty accessing my digital Ocean to deploy my changes, it used to be working fine, any ideas? @susanBuck 

<img width="1440" alt="Screen Shot 2020-11-24 at 8 24 12 PM" src="https://user-images.githubusercontent.com/15233956/100170205-202fb600-2e93-11eb-8e7d-3c92c0aa0cf9.png">

**Comment by ColeDCrawford** [comment]
You can use the DigitalOcean console to gain temporary access to the droplet to check out your settings.
