### ISSUE TITLE
Week 14 Part 5 Addendum - HTTPS

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-fall20#64]
Hi everyone - 

In this week's Part 5 video I cover the configs necessary for our authorization system to work on production.

As part of this, I spoke briefly about HTTPS but didn't get into the full details as I needed some additional time to work through a hiccup with the software (certbot) we're using for HTTPS setup.

I've since had time to address this and you can see the follow-up video with details here: 

**[Week 14 Part 5 Addendum - HTTPS](https://www.youtube.com/embed/w5iRWRchnl0?rel=0&showinfo=0)**

Corresponding notes:
+ [Authentication - Production](https://hesweb.dev/e28/notes/vue/auth-prod)
+ [Production server - HTTPS](https://hesweb.dev/e28/notes/production-server/https)

**Comment by christian-hilton** [comment]
Is HTTPS required for Project 3?  I just realized I wasn't sure, as I didn't see it specified in the requirements.

**Comment by susanBuck** [comment]
It's not required, no.

**Comment by christian-hilton** [comment]
Good to know, thanks @susanBuck !
