### ISSUE TITLE
401 Error and e28-api Not Showing Auth in Routes

### ISSUE THREAD

**Issue by pllealfunes** [susanBuck/e28-fall20#66]
Hi @susanBuck , I started to follow the steps to setup authentication and I ran into a ` 401 (Unauthorized)` error in my login page. I took a look at my e28-api and saw that the `auth` wasn't listed in the routes chart and it doesn't show the new Security Configs that's shown in the notes. I've run bash setup multiple times but it doesn't show. Could that be the reason for the 401 error?

<img width="1417" alt="Screen Shot 2020-12-07 at 1 45 56 PM" src="https://user-images.githubusercontent.com/51715816/101391605-94565a80-3892-11eb-85de-71312c201df9.png">

<img width="1392" alt="Screen Shot 2020-12-07 at 1 40 00 PM" src="https://user-images.githubusercontent.com/51715816/101391020-c1563d80-3891-11eb-8741-f6189f4e89e4.png">

**Comment by susanBuck** [comment]
Hi @pllealfunes -

Yes, it does appear you are missing the auth functionality in the API, indicating you may not have the latest changes/version. Running the bash setup script _should_ update it, so I'm not sure why that might be.

Can you run bash setup again and share the full output here for my own information?

After you do that, you can force it to update/grab the latest by doing the following:

From within `e28-api/`...
1. Make a backup copy of `core/.env` to save any existing environment configs
2. Delete the `core` directory
3. Run bash setup (it will re-clone the `core` directory for you)
4. Re-instante your `/core/.env` file from the backup

Then refresh the API dashboard in the browser and see if you have the new security configs and /auth route.

**Comment by pllealfunes** [comment]
Here's the output. Sorry, I didn't notice the `/routes` errors until now.

<img width="591" alt="Screen Shot 2020-12-07 at 2 17 37 PM" src="https://user-images.githubusercontent.com/51715816/101394771-ff099500-3896-11eb-8a84-23bf1fc20b05.png">

**Comment by pllealfunes** [comment]
Thank you, I was able to get the security configs and /auth route, and the 401 error disappeared.

**Comment by susanBuck** [comment]
Great! 

Based on the error shown under the "Update e28-api-core" step, you were facing the issue discussed here: https://github.com/susanBuck/e28-fall20/issues/65

To prevent this error from popping up again, update your _/e28-api/setup_ script by replacing its contents with [this latest version (1.0.4)](https://raw.githubusercontent.com/susanBuck/e28-api/master/setup)...

**Comment by pllealfunes** [comment]
Awesome, thanks again!
