### ISSUE TITLE
Update your e28-api setup scripts (current version: 1.0.4)

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-fall20#67]
Hi everyone,

In thread #65 we identified an issue that was causing the _"Updating e28-api core"_ step of the e28-api bash setup script to fail with this error:

```
=== Updating e28-api-core
error: Your local changes to the following files would be overwritten by merge:
	routes/api.php
	routes/web.php
Please commit your changes or stash them before you merge.
Aborting
```

**To rectify this issue, manually update your `e28-api/setup` file by replacing its contents with [the code found here](https://raw.githubusercontent.com/susanBuck/e28-api/master/setup) and run your `bash setup` script again.**

The latest version of the setup script is version **1.0.4** (you'll see this listed at the top of the setup script file).

If I need to make any additional changes to this file, I will update this thread with details.

**Comment by pllealfunes** [comment]
Should we also replace the one on production?  The output from bash setup mentions `Setup script version: 1.0.2`

**Comment by susanBuck** [comment]
Hi @pllealfunes - e28-api/setup is tracked in your repository so it's updated automatically when you sync changes from local.

**Comment by pllealfunes** [comment]
@susanBuck Great, thank you!
