### ISSUE TITLE
Bug fix: "Access Denied" when refreshing the "Add a Product" page

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-fall20#68]
Last week, in our Vue router code we set up a **beforeEach** navigation guard to protect certain routes (e.g. _Add a Product_ route) from being accessed by non-logged in users.

```js
router.beforeEach(async (to, from, next) => {

    const requiresAuth = to.matched.some(record => record.meta.requiresAuth);

    if (requiresAuth && !store.state.user) {
        next('/denied');
    }
    else {
        next();
    }
});
```

This worked when navigating between routes, but **there was a bug where you would see the _Access Denied_ route if you refreshed the browser while on a login-required route such as *Add a Product***

This occurred because the value for `store.state.user` was not available in the _beforeEach_ guard until the app was mounted and we dispatched _authUser_ from _App.vue_:

```js
mounted() {
    this.$store.dispatch('authUser');
}
```

To address this, we should move our dispatching of *authUser* to the router *beforeEach* guard, but we want to do so in such a way that we are not attempting to authorize the user every time we visit a new route.

This can be accomplished with the following updated *beforeEach* guard:

```js
router.beforeEach(async (to, from, next) => {

    const requiresAuth = to.matched.some(record => record.meta.requiresAuth);

    const decide = () => {
        if (requiresAuth && !store.state.user) {
            next('/denied');
        }
        else {
            next();
        }
    }
    
    // If we don't have the user yet, dispatch our Vuex authUser action
    if (store.state.user === null) {
        store.dispatch('authUser').then(() => {
            decide();
        });
    } else {
        decide();
    }

});
```

Note how the above code expects the dispatching of *authUser* to be a asynchronous call (see the usage of _then(...)_)

To accommodate this, we can adapt our *authUser* action to return a _Promise_:

```js
authUser(context) {
    return new Promise((resolve) => {
        axios.post('auth').then((response) => {
            if (response.data.authenticated) {
                context.commit('setUser', response.data.user);
            } else {
                context.commit('setUser', false);
            }

            resolve();
        });
    });
},
```

(More details on actions returning Promises here: [Vuex: Composing actions](https://vuex.vuejs.org/guide/actions.html#composing-actions))

**Comment by LDubya** [comment]
Quick question about this. What would happen under a slow connection? While the router has yet to decide which route to take, would it just be blank until the response from the post request is received?

**Comment by susanBuck** [comment]
@LDubya - Yes. 

To test this out/simulate it, in Chrome's web dev tools, under Network you can change the Network speed to "Slow 3g":

![image](https://user-images.githubusercontent.com/237711/102110452-2b776100-3e03-11eb-8764-abc53ba97f8c.png)
