### ISSUE TITLE
withCredentials breaks other API call

### ISSUE THREAD

**Issue by aeg224** [susanBuck/e28-fall20#69]
In my project, I'm calling two different API's. The e28-api requires 'withCredentials: true' for authentication. The other API does not, and breaks when this is set.

Is there a recommended way to resolve this? My first thought is to make two versions of axios (in app.js).

**Comment by susanBuck** [comment]
@aeg224 - You're correct - I'd initialize two instances of axios for the two different APIs. 

In fact, in order to use different base URLs, it seems like you would have already had to do that? (Unless you omitted the base URL and just specify it with each request).

**Comment by aeg224** [comment]
Yes, I was placing fully qualified URL's in the calls to two API's. Implementing two instances of Axios works great. I'll definitely remember to do this in the future.
