### ISSUE TITLE
Why would I declare variables using "let"?

### ISSUE THREAD

**Issue by kalbfled** [susanBuck/e28-fall20#7]
[reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Declarations)

Why would I use the _let_ keyword to declare JavaScript variables?  The only practical purpose I can see for it is to override variable names, like this:

```js
(function()
 {
     var x = 1;

     {
         let x = 2;
         console.log(x);
     }

     console.log(x);
})();
```
Output:
> 2
> 1

I would characterize this as a [code smell](https://en.wikipedia.org/wiki/Code_smell).

**Comment by LDubya** [comment]
I used to use `var` exclusively, but switched to the `let` and `const` paradigm once I started seeing how it was being used by other developers. The two advantages of `let` are 
- It prevents the same variable name from being declared more than once within its block/scope
- It prevents variables and their values from creeping outside of the scope that they're declared in

So if you did
```js
let x = 1;
let x = 2;
```
you'd get
```error
SyntaxError: Cannot declare a let variable twice: 'x'.
```

And if you did
```js
let x = 1;
{
    let x = 2;
}
```

you'd get
```error
SyntaxError: Can't create duplicate variable that shadows a global property: 'x'
```
 
Plus your example, where the variable defined by `let` does not exist outside its block

Hope this helps =)

**Comment by susanBuck** [comment]
Great summary by @LDubya 👍.

If you want to read more about this, I like this write-up: https://javascript.info/var

**Comment by iamakimmer** [comment]
Take your standard for loop:

```javascript
for (var i = 0; i < 5; i++) {
  console.log(i);
}
```

**var** isn't block scoped so after this code runs, **i** now has a value of 5, which could have unintended consequences. 

With **let**, 

```javascript
for (let j = 0; j < 5; j++) {
  console.log(i);
}
```

Since let is a block scoped variable, j only exists within the for loop. If you try to reference j later in your code, it will be undefined. Hope that helps too!

**Comment by kalbfled** [comment]
@iamakimmer  Thank you.  That makes sense.

@LDubya Doesn't [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) accomplish those benefits?

**Comment by LDubya** [comment]
> @LDubya Doesn't [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) accomplish those benefits?

Hmm. Beats me. What's the simplest way to accomplish the same block-scoping and single-definition functionality of `let`?

**Comment by ColeDCrawford** [comment]
> @LDubya Doesn't [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) accomplish those benefits?

Yes, but it has lots of other consequences too. If you're interested in preventing errors and writing stricter code, you could try Typescript. If you're coming from a Java/C background, or work with other strongly typed languages, it'll make sense right away - but if you're coming from JS/Python, it's some extra overhead. But the code usually has fewer bugs and plays better in larger ecosystems. There's also a Typescript linter for it that can force variables to have explicit types (`noImplicitAny`), prevent variables from possibly returning as undefined, etc.

**Comment by AdamNgu** [comment]
A nice little tip for the lazy is to default to using const and using let if you plan on redefining a variable: when your code editor or scripts throw up an error for redefining a const variable, simply update that variable to let.

Now you and any future developers will have certainty over which of your variables are redefined further in your code and which one are set in stone at definition.

**Comment by susanBuck** [comment]
That's a great tip, @AdamNgu!

Interesting input from all on this thread. Going to close this out now, but feel free to continue the discussion or start a new thread if there are any pending/new questions related to this.
