### ISSUE TITLE
Extending extra credit opportunity (need a review for one more project)

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-fall20#70]
Hi everyone,

Realized today we had one student project not on the [peer review spreadsheet](https://docs.google.com/spreadsheets/d/1f9v4sao-9QmqkUt690Trdr_wh3pJH1_3FrYNlV72Sqo/edit#gid=0) so they haven't received a review yet (https://github.com/Vikariusu/e28/tree/master/p2).

Because of this I am extending the second peer review extra credit opportunity to this Friday @ Midnight.

If you didn't get a chance to do a second peer review and would still like to, follow the procedures I outlined in [Week 14](https://hesweb.dev/e28/week/14).

**Comment by gboie** [comment]
I will do it, I didn't know I had to review two. Thank you!

**Comment by susanBuck** [comment]
@gboie -
Thanks!

To be clear, you don't *have* to review two. Completing a second review is an optional extra credit opportunity.

**Comment by gboie** [comment]
Thank you, I am sure I can use some extra credit :)

**Comment by gboie** [comment]
Done, thank you!
