### ISSUE TITLE
Errors Viewing Individual Recipe when Not Logged In

### ISSUE THREAD

**Issue by pllealfunes** [susanBuck/e28-fall20#71]
Hi @susanBuck ,

I was trying to add the functionality of adding and removing favorites but I get the following errors only when a user is not logged in. What I mean is that when a person logs in there are no errors but if you were to then log out or say a person just never logged in, they're just viewing as a guest, the errors pop up. I know that it has to do with the axios call in my mounted section because it looks to see if the recipe is a user's favorite. How can I keep my axios call without causing errors?
<img width="680" alt="Screen Shot 2020-12-09 at 10 37 19 PM" src="https://user-images.githubusercontent.com/51715816/101718796-f5875500-3a6f-11eb-9166-bae2a04200fa.png">
<img width="654" alt="Screen Shot 2020-12-09 at 10 37 44 PM" src="https://user-images.githubusercontent.com/51715816/101718808-f8824580-3a6f-11eb-8fd2-55ddaac9fa8f.png">

**Comment by susanBuck** [comment]
Hi @pllealfunes -

One approach I can think of to address this is to set up a watcher that listens for `user` to load, and when/if it does, *then* try and load favorites:

```js
watch: {
        // Watch for the user value to load
        user(userValue) {
            // Only attempt to load favorites if we have a user
            if (userValue) {
                axios
                    .get('/favorite/query?recipe_id=' + this.recipe.id)
                    .then(response => {
                        if (response.data.results.length > 0) {
                            // There should only ever be one unique match between a given user id and a given product id
                            // so we narrow the results down to [0]
                            this.favoriteId = response.data.results[0].id;
                            this.isFavorite = true;
                        }
                        console.log(response);
                    });
            }
        }
    },
```

**Comment by pllealfunes** [comment]
Thank you, it got rid of my errors. I do have another question though, when it comes to toggling between my `Add to Favorite` button and `Remove Button`, I noticed that I need to refresh the page a few times for the  remove button to show when a recipe is a favorite .Then when it does show and you go to another page, it goes back to the `Add to Favorite` button. How can I fix this issue?

**Comment by susanBuck** [comment]
Ah yes - ok - let's think through order of operations...

**Scenario 1)**
- We're on a recipe page, say _/recipe/1_
- We refresh the page, triggering the _authUser_ action in _App.vue -> mounted_ to be triggered
- This changes _user_ and the corresponding watcher in RecipePage triggers, which loads the favorite information.
- As a result, **we see an accurate representation of whether that recipe is on the favorites**.


**Scenario 2)**

- Now let's say we start on the homepage, _/_
- _user_ is loaded via the _authUser_ action in _App.vue -> mounted_
- We then navigate to the recipe page (_/recipe/1_). At this point, _user_ is already loaded, so our user watcher (that loads the favorites) is not triggered.
- As a result **we do _not_ see an accurate representation of whether that recipe is on the favorites**.

To address this, I suggest moving your ajax request to get the favorite details to its own method in _RecipePage_:

```php
getFavoriteDetails() {
            axios.get('/favorite/query?recipe_id=' + this.id).then(response => {
                if (response.data.results.length > 0) {
                    // There should only ever be one unique match between a given user id and a given product id
                    // so we narrow the results down to [0]
                    this.favoriteId = response.data.results[0].id;
                    this.isFavorite = true;
                }
            });
        }
```

This way we can invoke it from the watcher to handle the "_refresh the browser on this page_" scenario, _and_ in mounted to handle the "_came to this page from another page_" scenario.

Example:

```js
watch: { 
        // If we refresh the browser when on this route, the user won't be available until
        // authUser in App.vue is done executing. Once it's done, then we'll load favorites.
        user(userValue) {
            if (userValue) {
                this.getFavoriteDetails();
            }
        }
    },
    mounted() {
        // If we navigate to this route from another route, the user info will already be available
        // so we can go ahead and load favorites
        if (this.user) {
            this.getFavoriteDetails();
        }
    }
```

**Comment by pllealfunes** [comment]
It works fine now. Thank you for all the help, really appreciate it :)
