### ISSUE TITLE
API isn't connecting while running test

### ISSUE THREAD

**Issue by Ashley877** [susanBuck/e28-fall20#74]
I have created my test and my site works with my API but for some reason when I run the test it seems like the site no longer talks to the API. There should be two recipes that show up on the Recipes page. 
<img width="936" alt="Screen Shot 2020-12-13 at 11 06 52 AM" src="https://user-images.githubusercontent.com/55863118/102017205-7629a800-3d33-11eb-96c4-630e9f63f41f.png">

**Comment by Ashley877** [comment]
ahhh I just realized I had a typo.

**Comment by susanBuck** [comment]
@Ashley877 - Glad you caught it. :-)
