### ISSUE TITLE
Formatting Errors to Look Pretty

### ISSUE THREAD

**Issue by ARuzek** [susanBuck/e28-fall20#75]
### Why do my errors looks like this? (With brackets and quotes)

[ "The title field must be between 3 and 100 characters." ]
[ "The content field is required." ]

### Instead of this?
The title field must be between 3 and 100 characters.
The content field is required.

My Code (Same as in class example) 
```html
<ul v-if="errors">
          <li
            class="error"
            v-for="(error, index) in errors"
            :key="index"
          >
            {{ error}}
          </li>
        </ul>
```

**Comment by gboie** [comment]
This is how the validator.errors.all() outputs it, you can formatting it if
you want. I ended up outputting each error next to the specific input box
i.e. errors.title, etc.

**Comment by ARuzek** [comment]
@gboie Thank you! Yes, that fixed it!
