### ISSUE TITLE
Access Forbidden Error for e28-api domain

### ISSUE THREAD

**Issue by krishb09** [susanBuck/e28-fall20#76]
I'm trying to get both my client application and server api to have the same root domain-however, I keep on getting a 403 error when I try to load http://e28-api.krishbhes.loc 

Does anyone know what the issue might be?

![Screen Shot 2020-12-13 at 8 04 43 PM](https://user-images.githubusercontent.com/50959163/102029966-b6fade80-3d7e-11eb-986b-f1cdb7933fe5.png)

**Comment by balkasem** [comment]
i have the same issue, not able to resolve yet, would appreciate fi you share your experience resolving this
@susanBuck

**Comment by gboie** [comment]
Please share your web server configuration, looks like you are missing a
root directory for this configuration.

Thanks,
Gabriel

**Comment by krishb09** [comment]
Sure- here's my vhosts.conf file that I updated for the server 

Also added '127.0.0.1 e28-api.krishbhes.loc' to my hosts file. 

![Screen Shot 2020-12-14 at 10 59 30 AM](https://user-images.githubusercontent.com/50959163/102103831-79886680-3dfb-11eb-84c3-dff1384c0f38.png)

**Comment by gboie** [comment]
Thank you, that looks good assuming that path points to the api files. Can
you show the the files on that DocumentRoot path? (Include the permissions
for these files, they should belong to the Apache server user)

Thanks,
Gabriel

**Comment by krishb09** [comment]
![Screen Shot 2020-12-14 at 11 35 59 AM](https://user-images.githubusercontent.com/50959163/102108154-91161e00-3e00-11eb-9d73-bc8ac4689d65.png)


Is this what you mean? I don't think I updated anything in the .htaccess file

**Comment by susanBuck** [comment]
Hi @krishb09 -

Can you run the following command locally and share the output?

```
/Applications/XAMPP/bin/httpd -S
```

This will point out any errors that may exist in your VirtualHosts file that could be preventing your configuration from working.

(ref: https://hesweb.loc/e28/notes/local-server/local-domains#troubleshooting)

**Comment by krishb09** [comment]
![Screen Shot 2020-12-14 at 11 55 53 AM](https://user-images.githubusercontent.com/50959163/102110608-5e215980-3e03-11eb-9c9b-c4351e1b86d8.png)

So I ran the command in my e28-api folder and got this

**Comment by susanBuck** [comment]
Ok - I don't see any obvious issues based on that output.

Going through our checklist of local domain set up -
1. We know your hosts file is set up correctly because when you visit e28-api.krishbhes.loc you get an error indicating it is pointing to the Apache server.
2. We know your VirtualHosts file does not have any errors (based on the above output you shared).

Covering all our bases:

3. **Can you restart your Apache server via the XAMPP Control panel again?** You probably already did this, but it never hurts to do it again. 
4. Can you confirm that the document root path for the domain is correct - do this by running `cat /Applications/XAMPP/xamppfiles/htdocs/e28/e28-api/core/public/index.php` and confirm you see something like the following:

![image](https://user-images.githubusercontent.com/237711/102111488-75147b80-3e04-11eb-952c-4e47bf1db4e1.png)

**Comment by krishb09** [comment]
3) I think there might be an issue with my XAMPP Control panel- every time I click start for the Apache Web Server- it automatically 'stops'. (and I can't click 'restart'- seems to be disabled) 

However, when I do the command line version- 'service apache2 restart' I don't get any errors back. 
![Screen Shot 2020-12-14 at 12 15 24 PM](https://user-images.githubusercontent.com/50959163/102112693-105a2080-3e06-11eb-8d7b-9bd6979c5fe2.png)

4) Also yep I got the same output as above^ when running the 'cat' command

**Comment by gboie** [comment]
Probably unlikely to be a permissions issue, but what do you get if you do
an ls -l in your .../core/public directory?

Thanks,
Gabriel

**Comment by susanBuck** [comment]
@krishb09 -

I suspect you may have some other instance of Apache on your machine that is running, and conflicting with XAMPP's Apache.

Reasoning: 

When you visit http://e28-api.krishbhes.loc we do see evidence it's hitting an Apache server (based on the mention of Apache in the footer of the error page). This shouldn't be possible given XAMPP's Apache is not running, so it must be hitting some other Apache instance.

Also, a common cause of XAMPP's Apache not being able to start is some other Apache instance already using the port that it is trying to use.

Can you walk through the [troubleshooting steps described here](https://hesweb.dev/e28/notes/local-server/xampp-mac#troubleshooting) to try and address this? Report back on what that yields and we'll go from there. : )

**Comment by krishb09** [comment]
I ran through the troubleshooting steps and was able to get my Apache server running- 

but I'm getting this when trying to load my e28-api now: 

![Screen Shot 2020-12-14 at 3 08 43 PM](https://user-images.githubusercontent.com/50959163/102130127-6e92fd80-3e1e-11eb-94ca-8b8f7e732ccc.png)

**Comment by susanBuck** [comment]
@krishb09 - Excellent - that's good forward progress.

Based on the latest screenshot, it looks like the e28-api.krishbhes.loc domain is correctly resolving to your XAMPP Apache server.

However, it does not appear to be directly serving that site from the correct document root, as it appears to be defaulting to the "main" document root (the root of your htdocs folder).

Can you copy/paste the full contents of your VirtualHosts config file here so I can test it on my end?

**Comment by krishb09** [comment]
```
<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host.example.com
    DocumentRoot "/Applications/XAMPP/xamppfiles/docs/dummy-host.example.com"
    ServerName dummy-host.example.com
    ServerAlias www.dummy-host.example.com
    ErrorLog "logs/dummy-host.example.com-error_log"
    CustomLog "logs/dummy-host.example.com-access_log" common
</VirtualHost>

<VirtualHost *:80>
    ServerName practice.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e28/practice
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e28/practice>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName e28p1.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e28/p1
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e28/p1    >
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs
    <Directory /Applications/XAMPP/xamppfiles/htdocs>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>


<VirtualHost *:80>
    ServerName game.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e28/game
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e28/game>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName shoppingList.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e28/ShoppingLists
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e28/ShoppingLists>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName week4.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e28/Week4
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e28/Week4>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName wordscramble.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e28/Word-scramble
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e28/Word-scramble>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName project1.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e28/project1
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e28/project1>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>


<VirtualHost *:80>
    ServerName e28-api.krishbhes.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e28/e28-api/core/public/
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e28/e28-api/core/public/>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host2.example.com
    DocumentRoot "/Applications/XAMPP/xamppfiles/docs/dummy-host2.example.com"
    ServerName dummy-host2.example.com
    ErrorLog "logs/dummy-host2.example.com-error_log"
    CustomLog "logs/dummy-host2.example.com-access_log" common
</VirtualHost>
```


here's what I have in my vhosts file- @susanBuck  thank you!

**Comment by susanBuck** [comment]
Apologies for the delay - was on Zoom w/ another student. Testing your VirtualHosts on my end - will follow-up shortly. :)

**Comment by susanBuck** [comment]
I was able to run your VirtualHosts on my end without recreating the issue.

Any chance you could hop on Zoom now to do a screenshare and walk through this in real time? If so, my meeting URL is https://harvard.zoom.us/my/susanbuck.

**Comment by susanBuck** [comment]
If anyone else is reading/following this thread - @krishb09 and I resolved this in Zoom. The issue was a disconnect in how Apache was being restarted, preventing the changes from VirtualHosts from taking effect.
