### ISSUE TITLE
LinkedIn Networking 

### ISSUE THREAD

**Issue by gboie** [susanBuck/e28-fall20#78]
Hi all, hope everyone is doing great and wrapping up this great semester and getting ready for a well deserved break! Please connect and stay in touch, I am sure our paths will cross again. Best of luck and happy winter break!

https://www.linkedin.com/mwlite/in/gabriel-boie-2315b6

**Comment by LDubya** [comment]
Sure thing! I'd love to keep in touch. In addition to Github feel free to connect with me on:

Facebook ( https://www.facebook.com/realLarryWeru )
Linkedin ( https://www.linkedin.com/in/lawrenceweru/ )
Twitter ( http://twitter.com/LarryWeru )

I occasionally have remote front-end development work available for freelancers as well =)
