### ISSUE TITLE
Project 3 index page redirected

### ISSUE THREAD

**Issue by kalbfled** [susanBuck/e28-fall20#79]
I made a copy of p2 as "p3," reinstalled the modules as directed, and ran "npm run build".  When I visit https://e28p3.davejk.me, I'm redirected to https://www.davejk.me.  I edited my Apache config file as with my other subdomains, and I have `.htaccess` in /var/www/e28/p3/dist as required.  I have no idea at this point why I'm being directed.

Explicitly specifying the index page works: https://e28p3.davejk.me/index.html.

**Comment by susanBuck** [comment]
FYI just loaded it on my end and it's not redirecting. Made any DNS changes recently? Could be a cache issue?

**Comment by kalbfled** [comment]
It's a cache issue.  The site loads as expected in a private tab.  Crisis averted.  Thanks again, Susan!
