### ISSUE TITLE
Course Notes

### ISSUE THREAD

**Issue by ColeDCrawford** [susanBuck/e28-fall20#80]
I've found the notes super useful - both for class but also for a couple other Vue projects I've started since! Is there going to be a way to access these after the course ends? I know that the course site goes in and out of protected mode throughout the year, but a a snapshot of this "finished" notes guide for course alumni would be great.

**Comment by susanBuck** [comment]
Hi @ColeDCrawford - Please see the **[Week 15](https://hesweb.dev/e28/week/15) Part 1** video for details about an archive of course material I will be providing.
