### ISSUE TITLE
Blocked loading mixed active content

### ISSUE THREAD

**Issue by sneadthaman** [susanBuck/e28-fall20#81]
Sorry for the last minute issue but I am getting an error on initial page load on production:
![image](https://user-images.githubusercontent.com/30006142/102278116-41664e00-3ef7-11eb-8740-7917060f5bc7.png)

For some reason, the API calls are not happening over https eventhough I have changed the links on the production server in .env.production and .env

I am hosting the e28-api on a digital ocean server with HTTPS enabled and a certificate issued. That site works: https://e28-api.samjanvey.com

The Vue app  is being hosted on Netlify with HTTPS enabled : https://e28p3.samjanvey.com

Any ideas??

**Comment by sneadthaman** [comment]
Here is the github url: https://github.com/sneadthaman/e28_new/tree/master/p3/forgetmenot

**Comment by susanBuck** [comment]
Any chance you forgot to run `npm run build` locally before deploying your code? If you did, it would explain why it's still trying to ping the http version of the API address.

**Comment by sneadthaman** [comment]
Ahh I was just reading Gabriela's closed issue

Problem solved - thank you for the quick response!

**Comment by susanBuck** [comment]
np!
