### ISSUE TITLE
GitHub as Test Server

### ISSUE THREAD

**Issue by gboie** [susanBuck/e28-fall20#9]
Just discovered that you can actually test HTML/CSS/JavaScript directly in GitHub, if you go to your Repository --> Settings -->GitHub Pages. (You might have to enable if not enabled). Then you can copy that url i.e.https://gboie.github.io/e28/ and you can test your application (you might have to add /game to access the index.html in the game directory).

**Comment by vcavallo** [comment]
Good tip, @gboie! You might also like [CodePen](https://codepen.io/), if you haven't already heard of it.

**Comment by gboie** [comment]
Thank you @vcavallo, I occasionally use CodePen. I ran into some issues (Mixed content HTTP&HTTPS) so unfortunately none of these was ideal, so I ended up deploying our week 2 assignment on a DigitalOcean droplet.

**Comment by kalbfled** [comment]
Reference: https://docs.github.com/en/github/working-with-github-pages
